version: "3.3"

services:
  app:
    container_name: example
    build: .
    depends_on:
      - postgres
    ports: 
      - "3000:3000"
      - "9229:9229"
    networks:
      - default
    links:
      - postgres
    restart: always
    env_file: .env
    volumes: 
      - .:/app/
      - /app/node_modules
  postgres:
    container_name: example-db
    image: postgres:latest
    environment:
      POSTGRES_DB: 'example-db'
      POSTGRES_USER: 'localdbuser'
      POSTGRES_PASSWORD: 'localdbpassword'
